version: "3"
services:
  tcp_server:
    container_name: docker-python3-mongo
    restart: always
    build: ./app
    ports:
      - '7777:7777'
    volumes:
      - .:/app:/home/app
    depends_on:
      - db
    links:
      - db
    tty:
      true
  db:
    container_name: mongo
    image: mongo:4.0.9
    ports:
      - '27017:27017'
