version: "3"
services:
  tcp_server:
    container_name: docker-python3-mongo
    restart: always
    command: python3 -u tcp_server.py
    build: ./app
    ports:
      - '7777:7777'
    depends_on:
      - db
    links:
      - db
    tty:
      true
  db:
    container_name: db
    image: mongo:4.0.9
    command: mongod --port 27017
    ports:
      - '27017:27017'
